### ISSUE TITLE
Add fuzzy search of installed packages

### ISSUE THREAD

**Issue by X1Z53** [alt-gnome/apa#39]
I suggest adding functionality to search for the full package name with a fuzzy search from installed packages

**Comment by Rirusha** [comment]
```
apa list --mode=regex something
apa list --mode=fuzzy something
apa list --mode=plain (default) something
```

What you mind?

**Comment by X1Z53** [comment]
It seems to me, it seems, this is quite a good option. But why not just use `--plain`, `--regex` and `--fuzzy`?

But under the hood, it should work so that if `--plain` doesn't work, then do `--fuzzy'. And in parallel, if the request contains characters that are not used in package names (`.`, `*`, `()`etc.), then use `--regex`

**Comment by Rirusha** [comment]
> It seems to me, it seems, this is quite a good option. But why not just use `--plain`, `--regex` and `--fuzzy`?
> 
> But under the hood, it should work so that if `--plain` doesn't work, then do `--fuzzy`. And in parallel, if the request contains characters that are not used in package names (`.`, `*`, `()`, etc.), then use `--regex`

Doing this automatically is not the best solution. If I don't want to use fuzzy search in this case? Another solution: regex will be the default, fuzzy will work from the config. But if it needs to be disabled, it will be `--no-fuzzy`

**Comment by X1Z53** [comment]
Sounds good

**Comment by Rirusha** [comment]
Still, I didn't add a fuzzy search here. It didn't work well. But I added the `--installed` option to `search`.
