### ISSUE TITLE
Добавить аргумент поиска по выражению, подсветка результатов поиска.

### ISSUE THREAD

**Issue by OlegShchavelev** [alt-gnome/apa#49]
https://t.me/alt_gnome_chat/164634
> в APA так же неплохо также иметь поиск с подсветкой среди установленных файлов. По типу: 
> apa list| grep -E -i --color -- "(yandex)"

**Comment by X1Z53** [comment]
Это уже реализовано:

```shell
apa search --installed Yandex
```

**Comment by OlegShchavelev** [comment]
Здорово было реализовать и в list, search и list — это же разные команды.

**Comment by Rirusha** [comment]
> Здорово было реализовать и в list, search и list — это же разные команды.

list нужен для вывода всех пакетов, а не для поиска

**Comment by Rootovich** [comment]
> > Здорово было реализовать и в list, search и list — это же разные команды.
> 
> list нужен для вывода всех пакетов, а не для поиска

периодически нужен поиск среди установленных пакетов, а не в репо.

**Comment by Rirusha** [comment]
> > > Здорово было реализовать и в list, search и list — это же разные команды.
> > 
> > 
> > list нужен для вывода всех пакетов, а не для поиска
> 
> периодически нужен поиск среди установленных пакетов, а не в репо.

Для этого и есть
```
apa search --installed <regex>
```

**Comment by Rootovich** [comment]
> ```
> apa search --installed <regex>
> ```
Такой команды нет в `apa help`, кто бы мог подумать )

**Comment by Rootovich** [comment]
> ```
> apa search --installed <regex>
> ```
Кто бы мог подумать :) А в корень хелпа можете добавить ключики?

**Comment by Rirusha** [comment]
> > ```
> > apa search --installed <regex>
> > ```
> 
> Кто бы мог подумать... :) А в корень хелпа можете добавить ключики?

Согласен, надо бы добавить информацию в help, что поиск по установленным выполняется таким образом.
